### ISSUE TITLE
detailed work chunks for milestones 1a, 1b, 1c

### ISSUE THREAD

**Issue by michielbdejong** [pdsinterop/project-admin#8]
@michielbdejong to add detail to https://github.com/pdsinterop/project-admin/blob/master/milestones.md#1a-test-suite
@Potherca to add detail to https://github.com/pdsinterop/project-admin/blob/master/milestones.md#1b-standalone
@poef to add detail to https://github.com/pdsinterop/project-admin/blob/master/milestones.md#1c-nextcloud-integration

We want to try to break the currently active milestones up into chunks of 8 hours or less.

**Comment by michielbdejong** [comment]
Left to do:
* [ ] programmatically generate keys for nextcloud app
* [ ] programmatically obtain nextcloud cookie when running test-suites
* [ ] make stand-alone do the same as solid-nextcloud
* [ ] add our two servers to solid/test-suite
* [ ] write short milestone report and send RfP

**Comment by michielbdejong** [comment]
Upstreaming to solid/test-suite is blocked on https://gitter.im/solid/test-suite?at=5f71bc675b75b305ddcde563 since that repo is currently between maintainers.

I fixed the tests for node-solid-server now, so both NSS and Nextcloud now have 35/35 tests passing on the webid-provider test suite.

I merged the dev branch php-solid-server including the LoginController, so @ylebre can continue on top of that.

**Comment by michielbdejong** [comment]
Adding our servers to the upstream Solid test-suite in https://github.com/solid/test-suite/pull/102.

**Comment by michielbdejong** [comment]
Adding our app to the app store is waiting on https://github.com/nextcloud/app-certificate-requests/pull/347
